image: docker:latest
services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - develop
  script:
    - echo running tests

step-deploy-develop:
  stage: deploy
  only:
    - develop
  script:
    - sudo apt-get install -y python3-pip
    - sudo pip install docker-compose
    - sudo docker image prune -f
    - sudo docker-compose -f docker-compose.yml build --no-cache
    - sudo docker-compose -f docker-compose.yml down
    - sudo docker-compose -f docker-compose.yml up -d
  environment: develop

